import { createCanvas, GlobalFonts } from '@napi-rs/canvas';
import { getWorld } from './world-cache';
import { renderCartography } from '../src/engines/worldgen/cartography/render';
import { themeById } from '../src/engines/worldgen/cartography/theme';
import { buildHumanGeography, DEFAULT_HUMAN_PARAMS } from '../src/engines/worldgen/core/settlements';
import type { Ctx } from '../src/engines/worldgen/cartography/symbols';
GlobalFonts.registerFromPath('/usr/share/fonts/truetype/google-fonts/Lora-Variable.ttf', 'Lora');
const W = Number(process.env.OW || 1600), H = W / 2;
const world = getWorld({ seed: 'monstruo', width: 1024 });
const theme = themeById('wonder');
const geo = buildHumanGeography(world, DEFAULT_HUMAN_PARAMS);
const canvas = createCanvas(W, H);
const ctx = canvas.getContext('2d') as unknown as Ctx;
const go = (label: string, view?: {x:number;y:number;w:number;h:number}, layers?: object) => {
  const t0 = performance.now();
  const r = renderCartography(world, ctx, { theme, width: W, height: H, geography: geo, view, layers });
  console.log(`  ${label.padEnd(40)} ${(performance.now()-t0).toFixed(0).padStart(5)} ms  ${r.symbolCount} símbolos`);
};
const full = { x:0, y:0, w:world.width, h:world.height };
console.log(`salida ${W}x${H}\n`);
go('1º render (todo frío)', full);
go('2º render idéntico', full);
go('PANEO (mismo zoom, otra posición)', { ...full, x: 120 });
go('PANEO otra vez', { ...full, x: 260 });
const z = { x: 300, y: 140, w: world.width/3, h: world.height/3 };
go('ZOOM ×3 (bucket nuevo)', z);
go('PANEO con zoom ×3', { ...z, x: 340 });
go('ZOOM ×3,1 (mismo bucket)', { x: 300, y: 140, w: world.width/3.1, h: world.height/3.1 });
go('vista previa (mitad, sin símbolos)', full, { relief: false, forests: false, labels: false, settlements: false, roads: false });
const z6 = { x: 400, y: 180, w: world.width/6, h: world.height/6 };
go('ZOOM x6 (bucket frio)', z6);
go('PANEO con zoom x6', { ...z6, x: 430 });
const z14 = { x: 460, y: 200, w: world.width/14, h: world.height/14 };
go('ZOOM x14 (bucket frio)', z14);
go('PANEO con zoom x14', { ...z14, x: 470 });
