const es = {
  tools: 'Herramientas', hideTools: 'Ampliar mapa', showTools: 'Mostrar herramientas',
  changed: 'Hay ajustes por aplicar', unchanged: 'Estás viendo la configuración guardada',
  reset: 'Restablecer ajustes', alternative: 'Crear alternativa', alternativeName: 'Alternativa de',
  alternativeHint: 'Genera otro mundo con estos ajustes y conserva este tal como está.',
  replaceTitle: 'Regenerar este mundo',
  replaceHint: 'El terreno nuevo sustituirá al actual y se retirarán los trazos, nombres y lugares pintados. El cambio se aplicará al terminar y guardar correctamente.',
  locations: 'Chinchetas y regiones guardadas',
  keep: 'Conservar sus coordenadas', keepHint: 'Mantienen su posición geográfica, aunque el paisaje que hay debajo cambie.',
  clear: 'Retirarlas del mundo nuevo', clearHint: 'Empieza también sin chinchetas ni regiones guardadas.',
  replace: 'Sustituir terreno', cancel: 'Cancelar',
  saveFailed: 'No se pudo guardar. El mundo anterior sigue disponible; vuelve a intentarlo.',
  conflict: 'El mundo cambió mientras se generaba. Se han conservado los cambios guardados. Vuelve a generar desde la versión actual.',
  preparing: 'Guardando cambios pendientes…', applying: 'Guardando el nuevo mundo…',
  regionFailed: 'La región no se ha guardado todavía. Se conserva en esta vista para reintentar.',
  viewMode: 'Colorear el mapa por', progress: 'Generación del mundo',
  openOriginal: 'Abrir mundo de origen',
  recalculate: 'Recalcular clima y ríos', recalculateHint: 'Actualiza clima, corrientes, ríos, lagos y biomas a partir del relieve actual. Conserva tus trazos y se puede deshacer.',
  recalculating: 'Adaptando el mundo al relieve…', replaying: 'Restaurando la edición del mundo…', history: 'Restaurando el estado anterior…',
  environmentSave: 'Guardando el recálculo…', environmentError: 'No se pudo completar el cálculo. Tus cambios se conservan; vuelve a intentarlo.',
  environmentRetry: 'Volver a cargar la edición', environmentCancelled: 'La edición del mundo aún no se ha cargado.',
  environmentDone: 'Clima, ríos y lagos actualizados. Puedes deshacer el recálculo desde Pincel.',
};
const en: typeof es = {
  tools: 'Tools', hideTools: 'Expand map', showTools: 'Show tools',
  changed: 'Settings waiting to be applied', unchanged: 'Viewing the saved settings',
  reset: 'Reset settings', alternative: 'Create alternative', alternativeName: 'Alternative of',
  alternativeHint: 'Generate another world with these settings and keep this one as it is.',
  replaceTitle: 'Regenerate this world',
  replaceHint: 'The new terrain will replace the current world and remove painted strokes, names and places. The change applies only after generation and saving succeed.',
  locations: 'Waypoints and saved regions', keep: 'Keep their coordinates',
  keepHint: 'Keep their geographic position, even if the landscape underneath changes.',
  clear: 'Remove them from the new world', clearHint: 'Also start without waypoints or saved regions.',
  replace: 'Replace terrain', cancel: 'Cancel',
  saveFailed: 'Saving failed. The previous world is still available; try again.',
  conflict: 'The world changed during generation. Saved changes have been preserved. Generate again from the current version.',
  preparing: 'Saving pending changes…', applying: 'Saving the new world…',
  regionFailed: 'The region has not been saved yet. It remains in this view for retry.',
  viewMode: 'Color the map by', progress: 'World generation',
  openOriginal: 'Open original world',
  recalculate: 'Recalculate climate and rivers', recalculateHint: 'Update climate, currents, rivers, lakes and biomes from the current terrain. Your strokes are preserved and the action can be undone.',
  recalculating: 'Adapting the world to the terrain…', replaying: 'Restoring world edits…', history: 'Restoring the previous state…',
  environmentSave: 'Saving the recalculation…', environmentError: 'The calculation could not finish. Your edits are preserved; try again.',
  environmentRetry: 'Reload world edits', environmentCancelled: 'World edits have not been loaded yet.',
  environmentDone: 'Climate, rivers and lakes updated. You can undo the recalculation from Brush.',
};
export const worldWorkspaceCopy = (locale: string) => locale === 'en' ? en : es;
